#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Naofumi_REPO == "NaofumiBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL05hb2Z1bWlCb3QvTmFvZnVtaXVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $Naofumi_REPO == "NaofumiBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL05hb2Z1bWlCb3QvTmFvZnVtaXVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $Naofumi_REPO =~ $regex ]]
    then
        if [[ $Naofumi_REPO_BRANCH ]]
        then
            echo "${Naofumi_REPO}/archive/${Naofumi_REPO_BRANCH}.zip"
        else
            echo "${Naofumi_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL05hb2Z1bWlCb3QvTmFvZnVtaXVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="NaofumiBot.zip"
    echo "  ⚜Downloading NaofumiBot Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    NaofumiPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  NaofumiBot Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $LEGENDPATH
    echo "    • Starting NaofumiBot•    "
    echo "
    NaofumiBot
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
